name: notely
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  gap: ^3.0.1
  provider: ^6.1.2
  flutter_staggered_grid_view: ^0.7.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  draggable_fab: ^0.1.4
  flutter_speed_dial: ^7.0.0
  firebase_core: ^3.0.0
  firebase_auth: ^5.0.0
  country_picker: ^2.0.26
  loading_animation_widget: ^1.2.1
  google_ml_kit: ^0.18.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  speech_to_text: ^6.6.2
  avatar_glow: ^3.0.1
  flutter_zoom_drawer: ^3.2.0

dev_dependencies:
  hive_generator: ^2.0.1
  build_runner: ^2.4.10
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/fonts/
    - assets/icons/


  fonts:
    - family: nunito-black
      fonts:
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 900

    - family: nunito-bold
      fonts:
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700

    - family: nunito-extraBold
      fonts:
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800

    - family: nunito-regular
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf

    - family: titan
      fonts:
        - asset: assets/fonts/TitanOne-Regular.ttf


