// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAF2YHfcPzmMGy8K9ax8wk-9zQzvWj7Zhs',
    appId: '1:125223684195:web:82fde10423b6b4d9181056',
    messagingSenderId: '125223684195',
    projectId: 'note-taker-48d9e',
    authDomain: 'note-taker-48d9e.firebaseapp.com',
    storageBucket: 'note-taker-48d9e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPOWH0v9Mff3hjb4N99E-H82T4YSx49K4',
    appId: '1:125223684195:android:9d036ae82f282561181056',
    messagingSenderId: '125223684195',
    projectId: 'note-taker-48d9e',
    storageBucket: 'note-taker-48d9e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdd3990ERHnA2DfSlj1i9sVZRZwCq6oX4',
    appId: '1:125223684195:ios:3687ced599219138181056',
    messagingSenderId: '125223684195',
    projectId: 'note-taker-48d9e',
    storageBucket: 'note-taker-48d9e.appspot.com',
    iosBundleId: 'com.example.notely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdd3990ERHnA2DfSlj1i9sVZRZwCq6oX4',
    appId: '1:125223684195:ios:3687ced599219138181056',
    messagingSenderId: '125223684195',
    projectId: 'note-taker-48d9e',
    storageBucket: 'note-taker-48d9e.appspot.com',
    iosBundleId: 'com.example.notely',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAF2YHfcPzmMGy8K9ax8wk-9zQzvWj7Zhs',
    appId: '1:125223684195:web:bad3fa9846cee185181056',
    messagingSenderId: '125223684195',
    projectId: 'note-taker-48d9e',
    authDomain: 'note-taker-48d9e.firebaseapp.com',
    storageBucket: 'note-taker-48d9e.appspot.com',
  );
}
